# Generated by Django 5.1.6 on 2025-03-06 11:18

import uuid
import django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0002_alter_location_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('minimal', 'Minimal'), ('biasa', 'Biasa'), ('bahaya', 'Bahaya'), ('katastropik', 'Katastropik')], max_length=20),
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='HealthProtocolDisease',
                    fields=[
                        ('id', models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)),
                        ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocols', to='pt_backend.disease')),
                        ('health_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diseases', to='pt_backend.healthprotocol')),
                    ],
                    options={
                        'unique_together': {('health_protocol', 'disease')},
                    },
                ),
            ],
            database_operations=[]
        ),
    ]
