# Generated by Django 5.1.6 on 2025-03-07 09:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pt_backend", "0003_alter_case_status_alter_healthprotocoldisease_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthprotocoldisease",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
