# Generated by Django 5.1.6 on 2025-03-18 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0004_alter_healthprotocoldisease_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='severity',
            field=models.CharField(blank=True, choices=[('hospitalisasi', 'Hospitalisasi'), ('insiden', 'Insiden'), ('mortalitas', 'Mortalitas')], max_length=255),
        ),
    ]
