# Generated by Django 5.1.6 on 2025-03-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0005_case_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='severity',
            field=models.CharField(choices=[('hospitalisasi', 'Hospitalisasi'), ('insiden', 'Insiden'), ('mortalitas', 'Mortalitas')], max_length=255),
        ),
    ]
