# Generated by Django 5.1.6 on 2025-03-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0006_alter_case_severity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='location',
            name='province',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
