# Generated by Django 5.1.6 on 2025-03-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0007_rename_name_location_city_location_province'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(max_length=255),
        ),
    ]
