# Generated by Django 5.1.6 on 2025-03-19 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0008_alter_location_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img_url',
            field=models.URLField(blank=True),
        ),
    ]
