# Generated by Django 5.1.6 on 2025-04-16 05:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0010_alter_news_date_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('province', models.CharField(max_length=255)),
                ('temperature', models.DecimalField(decimal_places=6, max_digits=8)),
                ('percipitation', models.DecimalField(decimal_places=6, max_digits=8)),
                ('humidity', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='climate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='pt_backend.climate'),
        ),
    ]
