# Generated by Django 5.1.6 on 2025-04-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0011_climate_location_climate'),
    ]

    operations = [
        migrations.AddField(
            model_name='climate',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='climate',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
