# Generated by Django 5.1.6 on 2025-04-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0012_climate_month_climate_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='climate',
            name='percipitation',
        ),
        migrations.AddField(
            model_name='climate',
            name='precipitation',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='climate',
            name='humidity',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='climate',
            name='temperature',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
