# Generated by Django 5.1.6 on 2025-04-19 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0013_remove_climate_percipitation_climate_precipitation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='climate',
        ),
    ]
