# Generated by Django 5.1.6 on 2025-04-19 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pt_backend', '0014_remove_location_climate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='climate',
            name='precipitation',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='climate',
            name='year',
            field=models.IntegerField(),
        ),
    ]
