# Generated by Django 5.1.6 on 2025-04-21 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pt_backend", "0015_alter_climate_month_alter_climate_precipitation_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRoleRegistered",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Friendly name shown in the UI (defaults to role.name)",
                        max_length=100,
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower values appear earlier in dropdowns."
                    ),
                ),
                (
                    "role",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registration_meta",
                        to="pt_backend.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "registered role option",
                "verbose_name_plural": "registered role options",
                "ordering": ("sort_order", "role__name"),
            },
        ),
    ]
